version: '3'

services:
  
  elasticsearch:
    image: elasticsearch:7.17.6

    networks:
      - es

    ports:
      - 9200:9200
      - 9300:9300
  
    environment:
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD=elastic
      - discovery.type=single-node
  
  kibana:
    image: kibana:6.8.6
    networks:
      - es
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOST=htttp://elasticsearch:9200
    depends_on:
      - elasticsearch
networks:
  es:
    driver: bridge

